//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMMONRES.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COMMONRES.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 취소.
        /// </summary>
        internal static string BTN_CANCEL_TEXT {
            get {
                return ResourceManager.GetString("BTN_CANCEL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 닫기.
        /// </summary>
        internal static string BTN_CLOSE_TEXT {
            get {
                return ResourceManager.GetString("BTN_CLOSE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 확인.
        /// </summary>
        internal static string BTN_SUBMIT_TEXT {
            get {
                return ResourceManager.GetString("BTN_SUBMIT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User=USER1;Password=omega936;Database=C:\FBDB\FBRECORDING.FDB;DataSource=localhost;Port=3050;Dialect=3;Charset=KSC_5601;Role=;Connection lifetime=15;Pooling=true;Packet Size=8192;ServerType=0.
        /// </summary>
        internal static string DBCONSTR_FBSQL {
            get {
                return ResourceManager.GetString("DBCONSTR_FBSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User=USER1;Password=omega936;Database=&apos;C:\FBDB\FBRECORDING.FDB&apos;;DataSource={0};Port=3050;Dialect=3;Charset=KSC_5601;Role=;Connection lifetime=15; Pooling=true;Packet Size=8192;ServerType=0.
        /// </summary>
        internal static string DBCONSTR_FBSQL2 {
            get {
                return ResourceManager.GetString("DBCONSTR_FBSQL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider=Microsoft.Jet.OLEDB.4.0;Data Source=&apos;huensphoneDB.mdb&apos;.
        /// </summary>
        internal static string DBCONSTR_MDB {
            get {
                return ResourceManager.GetString("DBCONSTR_MDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=203.236.241.185; Initial Catalog=CIDSYSDB; Persist Security Info=True; User ID=huen; Password=huen.
        /// </summary>
        internal static string DBCONSTR_MSSQL {
            get {
                return ResourceManager.GetString("DBCONSTR_MSSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DBCONSTR_MYSQL {
            get {
                return ResourceManager.GetString("DBCONSTR_MYSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 112.169.24.102.
        /// </summary>
        internal static string DEFAULT_PBX_IPADDRESS {
            get {
                return ResourceManager.GetString("DEFAULT_PBX_IPADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31001.
        /// </summary>
        internal static string DEFAULT_PBX_PORT {
            get {
                return ResourceManager.GetString("DEFAULT_PBX_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eraser0 {
            get {
                object obj = ResourceManager.GetObject("eraser0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eraser1 {
            get {
                object obj = ResourceManager.GetObject("eraser1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이디를 입력해 주세요..
        /// </summary>
        internal static string ERR_USERID_EMPTY {
            get {
                return ResourceManager.GetString("ERR_USERID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 비밀번호를 입력해 주세요..
        /// </summary>
        internal static string ERR_USERPWD_EMPTY {
            get {
                return ResourceManager.GetString("ERR_USERPWD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_att {
            get {
                object obj = ResourceManager.GetObject("ic_att", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_attention {
            get {
                object obj = ResourceManager.GetObject("ic_attention", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_birthday {
            get {
                object obj = ResourceManager.GetObject("ic_birthday", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_cake {
            get {
                object obj = ResourceManager.GetObject("ic_cake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_close {
            get {
                object obj = ResourceManager.GetObject("ic_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_completed {
            get {
                object obj = ResourceManager.GetObject("ic_completed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_fees {
            get {
                object obj = ResourceManager.GetObject("ic_fees", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_incomming {
            get {
                object obj = ResourceManager.GetObject("ic_incomming", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_info {
            get {
                object obj = ResourceManager.GetObject("ic_info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_options {
            get {
                object obj = ResourceManager.GetObject("ic_options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_options1 {
            get {
                object obj = ResourceManager.GetObject("ic_options1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_outgoing {
            get {
                object obj = ResourceManager.GetObject("ic_outgoing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_pause {
            get {
                object obj = ResourceManager.GetObject("ic_pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_play {
            get {
                object obj = ResourceManager.GetObject("ic_play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_plus0 {
            get {
                object obj = ResourceManager.GetObject("ic_plus0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_plus1 {
            get {
                object obj = ResourceManager.GetObject("ic_plus1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_plus2 {
            get {
                object obj = ResourceManager.GetObject("ic_plus2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_props {
            get {
                object obj = ResourceManager.GetObject("ic_props", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_props2 {
            get {
                object obj = ResourceManager.GetObject("ic_props2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_refresh {
            get {
                object obj = ResourceManager.GetObject("ic_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_sms {
            get {
                object obj = ResourceManager.GetObject("ic_sms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_smses {
            get {
                object obj = ResourceManager.GetObject("ic_smses", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_smses1 {
            get {
                object obj = ResourceManager.GetObject("ic_smses1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_statis {
            get {
                object obj = ResourceManager.GetObject("ic_statis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_won {
            get {
                object obj = ResourceManager.GetObject("ic_won", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_attention {
            get {
                object obj = ResourceManager.GetObject("ico_attention", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_cake {
            get {
                object obj = ResourceManager.GetObject("ico_cake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_currency {
            get {
                object obj = ResourceManager.GetObject("ico_currency", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_gear {
            get {
                object obj = ResourceManager.GetObject("ico_gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_sms {
            get {
                object obj = ResourceManager.GetObject("ico_sms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_warning {
            get {
                object obj = ResourceManager.GetObject("ico_warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IDB_BANNER_001 {
            get {
                object obj = ResourceManager.GetObject("IDB_BANNER_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap incomming {
            get {
                object obj = ResourceManager.GetObject("incomming", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 윈도우 시작시 자동시작.
        /// </summary>
        internal static string LABEL_MAINPROPS_AUTOSTART {
            get {
                return ResourceManager.GetString("LABEL_MAINPROPS_AUTOSTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PBX IP :.
        /// </summary>
        internal static string LABEL_MAINPROPS_PBXIP {
            get {
                return ResourceManager.GetString("LABEL_MAINPROPS_PBXIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PBX Port :.
        /// </summary>
        internal static string LABEL_MAINPROPS_PBXPORT {
            get {
                return ResourceManager.GetString("LABEL_MAINPROPS_PBXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER ID :.
        /// </summary>
        internal static string LABEL_MAINPROPS_USERID {
            get {
                return ResourceManager.GetString("LABEL_MAINPROPS_USERID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to huensphoneDB.mdb.
        /// </summary>
        internal static string MDB_FILENAME {
            get {
                return ResourceManager.GetString("MDB_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 서버 등록에 실패 하였습니다.\n\r계속하여 같은 문제가 발생할 시에는 관리자에게 문의하여 주시기 바랍니다..
        /// </summary>
        internal static string MSG_ERR_REG {
            get {
                return ResourceManager.GetString("MSG_ERR_REG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 님으로 부터 전화가 왔습니다..
        /// </summary>
        internal static string MSG_INCOMMING {
            get {
                return ResourceManager.GetString("MSG_INCOMMING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [등록완료] 대기 상태 입니다..
        /// </summary>
        internal static string MSG_SUCCESS_REG {
            get {
                return ResourceManager.GetString("MSG_SUCCESS_REG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록 해제 완료!.
        /// </summary>
        internal static string MSG_SUCCESS_UNREG {
            get {
                return ResourceManager.GetString("MSG_SUCCESS_UNREG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 그룹을 선택 하세요..
        /// </summary>
        internal static string MSG_TXT_CB_CUST_GROUP_SEL {
            get {
                return ResourceManager.GetString("MSG_TXT_CB_CUST_GROUP_SEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 가족 관계를 선택하세요..
        /// </summary>
        internal static string MSG_TXT_CB_FR_SEL {
            get {
                return ResourceManager.GetString("MSG_TXT_CB_FR_SEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 가족 전화번호를 입력하세요..
        /// </summary>
        internal static string MSG_TXT_FT_TEL {
            get {
                return ResourceManager.GetString("MSG_TXT_FT_TEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 그룹을 선택하세요..
        /// </summary>
        internal static string MSG_TXT_POPUP_00 {
            get {
                return ResourceManager.GetString("MSG_TXT_POPUP_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 구분할 수 있는 가족명을 입력 하세요. \n\rex) 시윤이네.
        /// </summary>
        internal static string MSG_TXT_POPUP_01 {
            get {
                return ResourceManager.GetString("MSG_TXT_POPUP_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 주소를 입력하세요..
        /// </summary>
        internal static string MSG_TXT_POPUP_02 {
            get {
                return ResourceManager.GetString("MSG_TXT_POPUP_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 가족 정보와 해당 통화 내역이 모두 삭제 됩니다.\n\r계속 진행 하시겠습니까?\n\r통화 내역을 남겨 놓으시려면 &apos;현재상태&apos;를 &apos;졸업/사용하지않음&apos;으로 선택 후 수정하세요..
        /// </summary>
        internal static string MSG_TXT_POPUP_DELFAMILY {
            get {
                return ResourceManager.GetString("MSG_TXT_POPUP_DELFAMILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 가족정보 삭제.
        /// </summary>
        internal static string MSG_TXT_POPUP_DELFAMILY_TITLE {
            get {
                return ResourceManager.GetString("MSG_TXT_POPUP_DELFAMILY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 메모가 수정 되었습니다..
        /// </summary>
        internal static string MSG_TXT_POPUP_MODIMEMO1 {
            get {
                return ResourceManager.GetString("MSG_TXT_POPUP_MODIMEMO1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 개별통화 메모가 수정 되었습니다..
        /// </summary>
        internal static string MSG_TXT_POPUP_MODIMEMO2 {
            get {
                return ResourceManager.GetString("MSG_TXT_POPUP_MODIMEMO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록 된 고객 입니다..
        /// </summary>
        internal static string MSG_TXT_REGCUSTOMER {
            get {
                return ResourceManager.GetString("MSG_TXT_REGCUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록 되지 않은 고객 입니다..
        /// </summary>
        internal static string MSG_TXT_UNREGCUSTOMER {
            get {
                return ResourceManager.GetString("MSG_TXT_UNREGCUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap outgoing {
            get {
                object obj = ResourceManager.GetObject("outgoing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\Huen Communication\\Call Interceptor.
        /// </summary>
        internal static string REG_LOGIN {
            get {
                return ResourceManager.GetString("REG_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\Microsoft\\Windows\\CurrentVersion\Run.
        /// </summary>
        internal static string REG_MAIN_RUN {
            get {
                return ResourceManager.GetString("REG_MAIN_RUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\Huen Communication\\Call Recorder.
        /// </summary>
        internal static string REG_SUBKEY_CALLRECORDER {
            get {
                return ResourceManager.GetString("REG_SUBKEY_CALLRECORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\Huen Communication\\Call Interceptor.
        /// </summary>
        internal static string REG_SUBKEY_CRINTERCEPTOR {
            get {
                return ResourceManager.GetString("REG_SUBKEY_CRINTERCEPTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\Huen Communication\\Huen IPCC Server.
        /// </summary>
        internal static string REG_SUBKEY32_MAIN {
            get {
                return ResourceManager.GetString("REG_SUBKEY32_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\Huen Communication\\Huen IPCC\Desk Standard.
        /// </summary>
        internal static string REG_SUBKEY32_STA {
            get {
                return ResourceManager.GetString("REG_SUBKEY32_STA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\Huen Communication\\Huen IPCC Client.
        /// </summary>
        internal static string REG_SUBKEY32_SUB {
            get {
                return ResourceManager.GetString("REG_SUBKEY32_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\Wow6432Node\\Huen Communication\\Huen IPCC Server.
        /// </summary>
        internal static string REG_SUBKEY64_MAIN {
            get {
                return ResourceManager.GetString("REG_SUBKEY64_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\Wow6432Node\\Huen Communication\\Huen IPCC Client.
        /// </summary>
        internal static string REG_SUBKEY64_SUB {
            get {
                return ResourceManager.GetString("REG_SUBKEY64_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smartphone1 {
            get {
                object obj = ResourceManager.GetObject("smartphone1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smartphone2 {
            get {
                object obj = ResourceManager.GetObject("smartphone2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smartphone3 {
            get {
                object obj = ResourceManager.GetObject("smartphone3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ::선택::.
        /// </summary>
        internal static string TEXT_CB_FIRSTFIELD {
            get {
                return ResourceManager.GetString("TEXT_CB_FIRSTFIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brain Consulting IPCC - Huen Communication.
        /// </summary>
        internal static string TEXT_MAIN_TITLE {
            get {
                return ResourceManager.GetString("TEXT_MAIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 환경설정.
        /// </summary>
        internal static string TEXT_MAINPROPS_TITLE {
            get {
                return ResourceManager.GetString("TEXT_MAINPROPS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 부서명.
        /// </summary>
        internal static string TEXT_TREE_DEPART_ROOT {
            get {
                return ResourceManager.GetString("TEXT_TREE_DEPART_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 반이름.
        /// </summary>
        internal static string TEXT_TREE_GROUP_ROOT {
            get {
                return ResourceManager.GetString("TEXT_TREE_GROUP_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 서버재등록.
        /// </summary>
        internal static string TOOLTIP_MAIN_REG {
            get {
                return ResourceManager.GetString("TOOLTIP_MAIN_REG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 서버등록.
        /// </summary>
        internal static string TOOLTIP_MAIN_REREG {
            get {
                return ResourceManager.GetString("TOOLTIP_MAIN_REREG", resourceCulture);
            }
        }
    }
}
